name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
      - "fix"
      - "bugfix"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🔧 Maintenance"
    labels:
      - "chore"
      - "maintenance"
      - "refactor"
  - title: "⚡ Performance"
    labels:
      - "performance"
  - title: "💥 Breaking Changes"
    labels:
      - "breaking"
      - "breaking-change"

version-resolver:
  major:
    labels:
      - "breaking"
      - "breaking-change"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "bug"
      - "fix"
      - "bugfix"
      - "documentation"
      - "docs"
      - "chore"
      - "maintenance"
      - "refactor"
      - "performance"
  default: patch

exclude-labels:
  - "skip-changelog"
  - "dependencies"

autolabeler:
  - label: "feature"
    title:
      - '/^feat(\(.+\))?:/i'
      - '/^feature(\(.+\))?:/i'
  - label: "bug"
    title:
      - '/^fix(\(.+\))?:/i'
      - '/^bugfix(\(.+\))?:/i'
  - label: "documentation"
    title:
      - '/^docs(\(.+\))?:/i'
      - '/^doc(\(.+\))?:/i'
  - label: "chore"
    title:
      - '/^chore(\(.+\))?:/i'
      - '/^build(\(.+\))?:/i'
      - '/^ci(\(.+\))?:/i'
  - label: "refactor"
    title:
      - '/^refactor(\(.+\))?:/i'
  - label: "performance"
    title:
      - '/^perf(\(.+\))?:/i'
  - label: "breaking"
    title:
      - "/^.+!:/i"

template: |
  ## Pull Requests

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
