extends: default

ignore: |
  node_modules/
  .git/
  Library/
  obj/
  Temp/
  Samples~/

rules:
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy: disable
  document-start: disable
  comments-indentation: disable
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  new-lines:
    type: unix
  new-line-at-end-of-file: enable
  trailing-spaces: enable
  empty-lines:
    max: 1
    max-start: 0
    max-end: 1
