"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");
const childProcess = require("child_process");

const {
  BEGIN_MARKER,
  END_MARKER,
  selectRowsForVersion,
  alignTable,
  buildTable,
  buildBlock,
  blocksEquivalent,
  render
} = require("../unity/render-perf-doc.js");

const SCRIPT = path.resolve(__dirname, "..", "unity", "render-perf-doc.js");
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const MANAGED_PRETTIER = path.resolve(REPO_ROOT, "scripts", "run-managed-prettier.js");
const COMMITTED_DOC = path.resolve(REPO_ROOT, "docs", "architecture", "performance.md");

const LATEST = "6000.3.16f1";
const OLDER = "2022.3.45f1";

function platform(version, target = "Editor") {
  return `${target} Mono x64 Release (LinuxEditor; Unity ${version})`;
}

// A full set of nine scenario rows for one Unity version, plus optional noise.
function unityLog(version, { commit = "abc1234", target = "Editor" } = {}) {
  const scenarios = [
    ["UntargetedFlood_OneHandler", 25000000.125, 0, 1000.0],
    ["UntargetedFlood_FourHandlers_OnePriority", 12000000.5, 0, 1000.0],
    ["UntargetedFlood_FourHandlers_FourPriorities", 8000000.25, 0, 1000.0],
    ["TargetedFlood_OneListener", 18000000.0, 0, 1000.0],
    ["TargetedFlood_SixteenListeners", 4000000.0, 0, 1000.0],
    ["BroadcastFlood_OneHandler", 17000000.5, 0, 1000.0],
    ["InterceptorHeavy_FourInterceptors", 7000000.0, 0, 1000.0],
    ["PostProcessingHeavy_FourPostProcessors", 6000000.0, 0, 1000.0],
    ["RegistrationFlood_1000Types_FromColdBus", 0, 4096, 12.345]
  ];
  return scenarios
    .map(
      ([scenario, emits, alloc, ms]) =>
        `[TestRunner] {scenario:"${scenario}", platform:"${platform(
          version,
          target
        )}", commit:"${commit}", runIndex:-1, emitsPerSec:${emits}, allocatedBytesDelta:${alloc}, wallClockMs:${ms}}`
    )
    .join("\n");
}

function extractRows(content) {
  return require("../unity/extract-perf-baseline.js").extractRows(content);
}

function blockFor(version, options) {
  const rows = extractRows(unityLog(version, options));
  return buildBlock(selectRowsForVersion(rows, `Unity ${version}`), version);
}

// Run the repo's managed Prettier exactly as the markdown-json.yml gate does.
function managedPrettier(args) {
  return childProcess.spawnSync(process.execPath, [MANAGED_PRETTIER, ...args], {
    cwd: REPO_ROOT,
    encoding: "utf8",
    env: { ...process.env, DXMSG_HOOK_SKIP_INTEGRITY: "1" }
  });
}

// A seed doc that frames an AUTOGENERATED region with a Prettier-aligned
// placeholder table (mirrors docs/architecture/performance.md).
function seedDoc() {
  return [
    "# Performance Benchmarks",
    "",
    "Some intro prose.",
    "",
    BEGIN_MARKER,
    "",
    "The dispatch throughput table populates after the first scheduled benchmark run.",
    "",
    "| Scenario                       | Throughput / Wall clock | Allocated bytes |",
    "| ------------------------------ | ----------------------- | --------------- |",
    "| Pending first CI benchmark run | -                       | -               |",
    "",
    END_MARKER,
    "",
    "## Trailing Section",
    "",
    "Trailing prose stays intact.",
    ""
  ].join("\n");
}

describe("render-perf-doc selectRowsForVersion", () => {
  test("filters to the requested Unity version", () => {
    const rows = extractRows([unityLog(LATEST), unityLog(OLDER)].join("\n"));
    const selected = selectRowsForVersion(rows, `Unity ${LATEST}`);
    expect(selected.size).toBe(9);
    for (const row of selected.values()) {
      expect(row.platform).toContain(LATEST);
      expect(row.platform).not.toContain(OLDER);
    }
  });

  test("prefers the Editor platform when multiple platforms exist for one version", () => {
    const rows = extractRows(
      [unityLog(LATEST, { target: "Standalone" }), unityLog(LATEST, { target: "Editor" })].join(
        "\n"
      )
    );
    const selected = selectRowsForVersion(rows, `Unity ${LATEST}`);
    for (const row of selected.values()) {
      expect(row.platform).toContain("Editor");
    }
  });
});

describe("render-perf-doc alignTable (Prettier-aligned output)", () => {
  test("pads every column to max(3, widest cell) like Prettier GFM tables", () => {
    const table = alignTable([
      ["A", "Long header here", "C"],
      ["x", "y", "zzzzzzzzzz"]
    ]);
    expect(table).toBe(
      [
        "| A   | Long header here | C          |",
        "| --- | ---------------- | ---------- |",
        "| x   | y                | zzzzzzzzzz |"
      ].join("\n")
    );
  });

  test("buildTable emits aligned pipes, not compact `| --- |`", () => {
    const rows = extractRows(unityLog(LATEST));
    const table = buildTable(selectRowsForVersion(rows, `Unity ${LATEST}`), LATEST);
    const lines = table.split("\n");
    // Separator row is filled with dashes to the column width (> 3), never the
    // compact 3-dash form that the required Prettier gate would reflow.
    expect(lines[1]).toMatch(/^\| -{4,} \| -+ \| -+ \|$/);
    expect(lines[1]).not.toBe("| --- | --- | --- |");
    // Header cells are space-padded so the pipes line up.
    expect(lines[0]).toContain("| Scenario  ");
  });
});

describe("render-perf-doc buildBlock", () => {
  test("renders throughput rows and a wall-clock registration row in stable order", () => {
    const block = blockFor(LATEST);

    expect(block.startsWith(BEGIN_MARKER)).toBe(true);
    expect(block.endsWith(END_MARKER)).toBe(true);
    expect(block).toContain(`Unity ${LATEST}`);
    expect(block).toContain("`abc1234`");
    expect(block).toContain("25.00 M emits/sec");
    expect(block).toContain("12.345 ms");
    expect(block).toContain("4,096 B");

    const firstIndex = block.indexOf("UntargetedFlood_OneHandler");
    const lastIndex = block.indexOf("RegistrationFlood_1000Types_FromColdBus");
    expect(firstIndex).toBeGreaterThan(0);
    expect(lastIndex).toBeGreaterThan(firstIndex);
  });
});

// CRITICAL-1 REGRESSION GUARD: the prior renderer emitted compact `| --- |`
// pipes that the repo's REQUIRED markdown prettier gate reflows, so the
// auto-PR was always red. These tests fail if the rendered output is not
// already Prettier-clean.
describe("render-perf-doc Prettier parity (CRITICAL-1)", () => {
  let tempDir;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "dxm-render-prettier-"));
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  test("a freshly rendered doc passes managed Prettier --check unchanged", () => {
    const docPath = path.join(tempDir, "performance.md");
    const inputPath = path.join(tempDir, "unity.log");
    fs.writeFileSync(docPath, seedDoc(), "utf8");
    fs.writeFileSync(inputPath, unityLog(LATEST), "utf8");

    const result = render({
      inputs: [inputPath],
      doc: docPath,
      unityVersion: LATEST,
      platformSubstring: "",
      tolerance: 0.02
    });
    expect(result.changed).toBe(true);
    fs.writeFileSync(docPath, result.content, "utf8");

    const before = fs.readFileSync(docPath, "utf8");
    const write = managedPrettier(["--write", docPath]);
    expect(write.status).toBe(0);
    // Prettier left the rendered table byte-for-byte unchanged.
    expect(fs.readFileSync(docPath, "utf8")).toBe(before);

    const check = managedPrettier(["--check", docPath]);
    expect(check.status).toBe(0);
  });

  test("the committed performance.md passes managed Prettier --check", () => {
    // The committed doc must ship Prettier-clean AND contain exactly one
    // marker pair so the renderer can operate on it (the prior implementation
    // shipped a doc with NO markers, which would throw at render time).
    const content = fs.readFileSync(COMMITTED_DOC, "utf8");
    expect(content.split(BEGIN_MARKER)).toHaveLength(2);
    expect(content.split(END_MARKER)).toHaveLength(2);

    const check = managedPrettier(["--check", COMMITTED_DOC]);
    expect(check.status).toBe(0);
  });
});

describe("render-perf-doc blocksEquivalent (idempotence)", () => {
  test("treats jitter within tolerance as unchanged", () => {
    const base = blockFor(LATEST);
    // 25000000.125 -> 25.00 M; +1% jitter keeps the rounded display identical
    // and stays within the 2% tolerance.
    const jitter = unityLog(LATEST).replace("25000000.125", "25250000.0");
    const jittered = buildBlock(selectRowsForVersion(extractRows(jitter), `Unity ${LATEST}`), LATEST);
    expect(blocksEquivalent(base, jittered, 0.02)).toBe(true);
  });

  test("treats a real regression beyond tolerance as changed", () => {
    const base = blockFor(LATEST);
    const regressed = unityLog(LATEST).replace("25000000.125", "12000000.0");
    const regressedBlock = buildBlock(
      selectRowsForVersion(extractRows(regressed), `Unity ${LATEST}`),
      LATEST
    );
    expect(blocksEquivalent(base, regressedBlock, 0.02)).toBe(false);
  });

  // CRITICAL-2a REGRESSION GUARD: the prior buildBlock put the commit SHA
  // INSIDE the compared region and blocksEquivalent compared digit-stripped
  // skeletons line-by-line, so a changed SHA alone (master advances every run)
  // forced a rewrite -> churn PR almost every run. Equivalence must now ignore
  // the provenance line and compare table rows only.
  test("a changed commit hash with in-tolerance numbers is NOT a change", () => {
    const base = blockFor(LATEST, { commit: "0000aaa" });
    const sameNumbersNewCommit = blockFor(LATEST, { commit: "ffff999" });
    expect(sameNumbersNewCommit).not.toBe(base); // provenance line differs
    expect(blocksEquivalent(base, sameNumbersNewCommit, 0.02)).toBe(true);
  });

  // CRITICAL-2b REGRESSION GUARD: equivalence must be insensitive to Prettier's
  // column alignment so an aligned committed block matches a freshly rendered
  // (also aligned) block, and a hand-authored compact block still matches.
  test("compact-pipe and Prettier-aligned blocks are equivalent", () => {
    const aligned = blockFor(LATEST);
    const compact = aligned
      .split("\n")
      .map((line) =>
        line.startsWith("|")
          ? "| " +
            line
              .replace(/^\|/, "")
              .replace(/\|$/, "")
              .split("|")
              .map((cell) => {
                const trimmed = cell.trim();
                return /^-+$/.test(trimmed) ? "---" : trimmed;
              })
              .join(" | ") +
            " |"
          : line
      )
      .join("\n");
    expect(compact).not.toBe(aligned);
    expect(blocksEquivalent(aligned, compact, 0.02)).toBe(true);
  });
});

describe("render-perf-doc render (doc rewrite)", () => {
  let tempDir;
  let docPath;
  let inputPath;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "dxm-render-perf-"));
    docPath = path.join(tempDir, "performance.md");
    inputPath = path.join(tempDir, "unity.log");
    fs.writeFileSync(docPath, seedDoc(), "utf8");
    fs.writeFileSync(inputPath, unityLog(LATEST), "utf8");
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  function renderDoc(overrides = {}) {
    return render({
      inputs: [inputPath],
      doc: docPath,
      unityVersion: LATEST,
      platformSubstring: "",
      tolerance: 0.02,
      ...overrides
    });
  }

  test("replaces the placeholder block and preserves surrounding sections", () => {
    const result = renderDoc();
    expect(result.changed).toBe(true);
    expect(result.content).toContain("# Performance Benchmarks");
    expect(result.content).toContain("## Trailing Section");
    expect(result.content).toContain("Trailing prose stays intact.");
    expect(result.content).toContain("25.00 M emits/sec");
    expect(result.content).not.toContain("Pending first CI benchmark run");
    expect(result.content.split(BEGIN_MARKER)).toHaveLength(2);
    expect(result.content.split(END_MARKER)).toHaveLength(2);
  });

  test("is idempotent: a second render of the same numbers is a byte-identical no-op", () => {
    const first = renderDoc();
    fs.writeFileSync(docPath, first.content, "utf8");

    const second = renderDoc();
    expect(second.changed).toBe(false);
    expect(second.content).toBe(first.content);
  });

  // CRITICAL-2a end-to-end: after a real run lands, a later run with a DIFFERENT
  // commit but in-tolerance numbers must NOT rewrite the doc (no churn PR).
  test("does not rewrite when only the commit changed and numbers are in tolerance", () => {
    const first = renderDoc();
    fs.writeFileSync(docPath, first.content, "utf8");

    // New run: different commit, jitter within tolerance.
    fs.writeFileSync(
      inputPath,
      unityLog(LATEST, { commit: "deadbee" }).replace("25000000.125", "25200000.0"),
      "utf8"
    );
    const second = renderDoc();
    expect(second.changed).toBe(false);
    expect(second.content).toBe(first.content);
  });

  test("rewrites (and refreshes the commit) on a real regression", () => {
    const first = renderDoc();
    fs.writeFileSync(docPath, first.content, "utf8");

    fs.writeFileSync(
      inputPath,
      unityLog(LATEST, { commit: "cafef00" }).replace("25000000.125", "12000000.0"),
      "utf8"
    );
    const second = renderDoc();
    expect(second.changed).toBe(true);
    expect(second.content).toContain("`cafef00`");
    // The regressed first-scenario row now reads 12.00 M emits/sec (alignment
    // padding is incidental, so match the row by its trimmed cells).
    expect(second.content).toMatch(
      /\|\s*UntargetedFlood_OneHandler\s*\|\s*12\.00 M emits\/sec\s*\|\s*0 B\s*\|/
    );
  });

  // LOW-1 REGRESSION GUARD: duplicate markers previously caused a silent
  // partial rewrite (first BEGIN / first END). Now the renderer refuses.
  test("throws when the doc contains more than one marker pair", () => {
    const doubled = seedDoc() + "\n" + [BEGIN_MARKER, "stray", END_MARKER].join("\n") + "\n";
    fs.writeFileSync(docPath, doubled, "utf8");
    expect(() => renderDoc()).toThrow(/exactly one AUTOGENERATED dispatch-throughput marker pair/);
  });

  test("throws when the doc is missing the markers entirely", () => {
    fs.writeFileSync(docPath, "# No markers here\n\nbody\n", "utf8");
    expect(() => renderDoc()).toThrow(/Could not find AUTOGENERATED dispatch-throughput markers/);
  });
});

describe("render-perf-doc CLI", () => {
  let tempDir;
  let docPath;
  let inputPath;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "dxm-render-perf-cli-"));
    docPath = path.join(tempDir, "performance.md");
    inputPath = path.join(tempDir, "unity.log");
    fs.writeFileSync(docPath, seedDoc(), "utf8");
    fs.writeFileSync(inputPath, unityLog(LATEST), "utf8");
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  test("writes the doc and exits 0", () => {
    const result = childProcess.spawnSync(
      process.execPath,
      [SCRIPT, "--input", inputPath, "--doc", docPath, "--unity-version", LATEST],
      { encoding: "utf8" }
    );
    expect(result.status).toBe(0);
    expect(fs.readFileSync(docPath, "utf8")).toContain("25.00 M emits/sec");
  });

  test("a CLI-written doc passes managed Prettier --check (no compact-pipe drift)", () => {
    const write = childProcess.spawnSync(
      process.execPath,
      [SCRIPT, "--input", inputPath, "--doc", docPath, "--unity-version", LATEST],
      { encoding: "utf8" }
    );
    expect(write.status).toBe(0);
    const check = managedPrettier(["--check", docPath]);
    expect(check.status).toBe(0);
  });

  test("--check exits 3 when the doc would change and 0 when current", () => {
    const drift = childProcess.spawnSync(
      process.execPath,
      [SCRIPT, "--input", inputPath, "--doc", docPath, "--unity-version", LATEST, "--check"],
      { encoding: "utf8" }
    );
    expect(drift.status).toBe(3);

    childProcess.spawnSync(
      process.execPath,
      [SCRIPT, "--input", inputPath, "--doc", docPath, "--unity-version", LATEST],
      { encoding: "utf8" }
    );
    const current = childProcess.spawnSync(
      process.execPath,
      [SCRIPT, "--input", inputPath, "--doc", docPath, "--unity-version", LATEST, "--check"],
      { encoding: "utf8" }
    );
    expect(current.status).toBe(0);
  });

  test("fails when no rows match the requested Unity version", () => {
    const result = childProcess.spawnSync(
      process.execPath,
      [SCRIPT, "--input", inputPath, "--doc", docPath, "--unity-version", "9999.9.9f9"],
      { encoding: "utf8" }
    );
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("No DispatchThroughputBenchmarks rows matched");
  });
});
