<#
.SYNOPSIS
    Syncs package metadata to the SVG banner.
.DESCRIPTION
    Reads the version from package.json, calculates the rounded repository
    test count from test files, and updates docs/images/DxMessaging-banner.svg
    (the canonical location). The site/ copy is regenerated by MkDocs and is
    gitignored, so it is not synced here.

    Called by the pre-commit hook before each commit is created.

    NOTE: This script is optional in the pre-commit workflow. If PowerShell
    is not available, the hook skips banner sync because:
    - The banner version is purely cosmetic (affects README appearance only)
    - Contributors without PowerShell should not be blocked from committing
    - The banner can be updated manually or via CI if needed
#>

$ErrorActionPreference = 'Stop'

# Get the script directory and navigate to repo root
$scriptDir = $PSScriptRoot
$repoRoot = Split-Path -Parent $scriptDir

# Construct paths for package.json and the canonical SVG
$packageJsonPath = Join-Path $repoRoot "package.json"
$svgPath = Join-Path $repoRoot "docs" "images" "DxMessaging-banner.svg"

function Remove-SourceComments {
    param([string]$Content)

    $withoutBlockComments = [regex]::Replace($Content, '/\*[\s\S]*?\*/', '')
    return [regex]::Replace($withoutBlockComments, '(?m)(^|[^:])//.*$', '$1')
}

function Add-StrippedJavaScriptChar {
    param(
        [System.Text.StringBuilder]$Builder,
        [char]$Character
    )

    if ($Character -eq [char]10 -or $Character -eq [char]13) {
        [void]$Builder.Append($Character)
    } else {
        [void]$Builder.Append(' ')
    }
}

function Remove-JavaScriptNonCode {
    param([string]$Content)

    if ([string]::IsNullOrEmpty($Content)) {
        return $Content
    }

    $builder = [System.Text.StringBuilder]::new($Content.Length)
    $state = 'Code'
    $quote = [char]0
    $escaped = $false
    $singleQuote = [char]39
    $doubleQuote = [char]34
    $backtick = [char]96
    $slash = [char]47
    $asterisk = [char]42
    $backslash = [char]92
    $lineFeed = [char]10
    $carriageReturn = [char]13
    $i = 0

    while ($i -lt $Content.Length) {
        $char = $Content[$i]
        $next = if ($i + 1 -lt $Content.Length) { $Content[$i + 1] } else { [char]0 }

        switch ($state) {
            'Code' {
                if ($char -eq $slash -and $next -eq $slash) {
                    Add-StrippedJavaScriptChar -Builder $builder -Character $char
                    Add-StrippedJavaScriptChar -Builder $builder -Character $next
                    $i += 2
                    $state = 'LineComment'
                    continue
                }
                if ($char -eq $slash -and $next -eq $asterisk) {
                    Add-StrippedJavaScriptChar -Builder $builder -Character $char
                    Add-StrippedJavaScriptChar -Builder $builder -Character $next
                    $i += 2
                    $state = 'BlockComment'
                    continue
                }
                if ($char -eq $singleQuote -or $char -eq $doubleQuote -or $char -eq $backtick) {
                    Add-StrippedJavaScriptChar -Builder $builder -Character $char
                    $quote = $char
                    $escaped = $false
                    $i++
                    $state = 'String'
                    continue
                }

                [void]$builder.Append($char)
                $i++
                continue
            }
            'LineComment' {
                Add-StrippedJavaScriptChar -Builder $builder -Character $char
                $i++
                if ($char -eq $lineFeed -or $char -eq $carriageReturn) {
                    $state = 'Code'
                }
                continue
            }
            'BlockComment' {
                Add-StrippedJavaScriptChar -Builder $builder -Character $char
                if ($char -eq $asterisk -and $next -eq $slash) {
                    Add-StrippedJavaScriptChar -Builder $builder -Character $next
                    $i += 2
                    $state = 'Code'
                    continue
                }
                $i++
                continue
            }
            'String' {
                Add-StrippedJavaScriptChar -Builder $builder -Character $char
                $i++
                if ($escaped) {
                    $escaped = $false
                    continue
                }
                if ($char -eq $backslash) {
                    $escaped = $true
                    continue
                }
                if ($char -eq $quote) {
                    $state = 'Code'
                }
                continue
            }
        }
    }

    return $builder.ToString()
}

function Get-RepositoryTestCount {
    param([string]$Root)

    $testRoots = @('Tests', 'SourceGenerators', 'scripts')
    $count = 0

    foreach ($relativeRoot in $testRoots) {
        $absoluteRoot = Join-Path $Root $relativeRoot
        if (-not (Test-Path $absoluteRoot)) {
            continue
        }

        $files = Get-ChildItem -Path $absoluteRoot -Recurse -File | Where-Object {
            $_.Name -match '(?:Test|Tests)\.cs$' -or $_.Name -match '\.(?:test|spec)\.js$'
        }

        foreach ($file in $files) {
            $content = Remove-SourceComments -Content (Get-Content $file.FullName -Raw)
            if ($file.Extension -eq '.cs') {
                $count += [regex]::Matches($content, '\[(?:UnityTest|Test|TestCase|TestCaseSource|Theory|Fact)\b').Count
            } else {
                $content = Remove-JavaScriptNonCode -Content (Get-Content $file.FullName -Raw)
                $count += [regex]::Matches($content, '(?<![\w.])(?:test|it)\s*\(').Count
            }
        }
    }

    return $count
}

function Get-RoundedTestCount {
    param([int]$TestCount)

    $rounded = [int]([Math]::Floor($TestCount / 100) * 100)
    if ($rounded -lt 1) {
        return $TestCount
    }

    return $rounded
}

# Check if package.json exists
if (-not (Test-Path $packageJsonPath)) {
    Write-Error "package.json not found at: $packageJsonPath"
    exit 1
}

# Check that the SVG exists
if (-not (Test-Path $svgPath)) {
    Write-Error "SVG banner not found at: $svgPath"
    exit 1
}

# Read version from package.json
try {
    $packageJson = Get-Content $packageJsonPath -Raw | ConvertFrom-Json
    $version = $packageJson.version
    if (-not $version) {
        Write-Error "No version field found in package.json"
        exit 1
    }
    # Validate semver format (X.Y.Z with optional pre-release/build metadata)
    if ($version -notmatch '^\d+\.\d+\.\d+') {
        Write-Error "Invalid version format in package.json: $version (expected semver X.Y.Z)"
        exit 1
    }
} catch {
    Write-Error "Failed to read package.json: $_"
    exit 1
}

try {
    $testCount = Get-RepositoryTestCount -Root $repoRoot
    $roundedTestCount = Get-RoundedTestCount -TestCount $testCount
    $testCountLabel = "$roundedTestCount+ Tests"
} catch {
    Write-Error "Failed to calculate repository test count: $_"
    exit 1
}

# Pattern to find version text in the SVG
# SYNC: Keep pattern in sync with the SVG banner format
# The pattern anchors to the Version badge comment to avoid matching other version-like text
# Note: Uses .*? (non-greedy) for comment body to match anything up to -->
#
# PATTERN SAFETY: The [^>]* patterns used here for XML tag attributes (e.g., <g[^>]*>) are safe because:
# 1. In well-formed XML, the closing '>' of a tag is always outside quoted attribute values
# 2. The AttValue grammar (XML 1.0 section 2.3) ensures quotes are properly matched, so the
#    parser finds the '>' that closes the tag, not any '>' that might appear in attribute values
# 3. This SVG file is a controlled, project-maintained asset with validated format
# 4. This differs from XML comments where '>' IS allowed (hence .*? for the comment body)
# Note: Malformed XML (mismatched quotes) would break this assumption, but such files fail parsing anyway
$versionPattern = '<!-- Version badge \(top right\).*?-->\s*<g[^>]*>\s*<rect[^>]*/>\s*<text[^>]*>v\d+\.\d+\.\d+[^<]*</text>\s*</g>'
# SYNC: This heredoc must remain BYTE-IDENTICAL to the version-badge block in
# docs/images/DxMessaging-banner.svg. scripts/validate-banner.js enforces the
# byte-equality. If you change attributes here, change them in the SVG in the
# same commit and run validate-banner.js to confirm.
$newVersionText = @"
<!-- Version badge (top right) - text must contain vX.Y.Z for version sync -->
  <g transform="translate(720, 18)">
    <rect x="0" y="0" width="62" height="22" rx="11" ry="11" fill="#e94560" opacity="0.95" filter="url(#softShadow)"/>
    <text x="31" y="15" text-anchor="middle" font-family="'SF Mono', 'Fira Code', monospace" font-size="11" font-weight="700" fill="#ffffff" letter-spacing="0.5">v$version</text>
  </g>
"@

# Pattern to find the feature-row test count label. The label is updated from
# repository test files so it does not drift as coverage changes.
$testCountPattern = '(<text(?=[^>]*\bx="20")(?=[^>]*\by="13")(?=[^>]*\bfill="#00d9ff")[^>]*>)(\d+\+ Tests)(</text>)'

# Read the SVG content
try {
    $svgContent = Get-Content $svgPath -Raw
} catch {
    Write-Error "Failed to read SVG file ${svgPath}: $_"
    exit 1
}

# Check if the pattern matches
if ($svgContent -notmatch $versionPattern) {
    Write-Error "Could not find version pattern in: $svgPath"
    Write-Error "Banner format may have changed. Expected pattern: $versionPattern"
    exit 1
}

if ($svgContent -notmatch $testCountPattern) {
    Write-Error "Could not find test-count feature label in: $svgPath"
    Write-Error "Banner format may have changed. Expected pattern: $testCountPattern"
    exit 1
}

# Extract just the version number from the match for comparison
$currentMatch = [regex]::Match($svgContent, $versionPattern).Value
$currentVersionMatch = [regex]::Match($currentMatch, '>v(\d+\.\d+\.\d+[^<]*)</text>')
$currentTestCountMatch = [regex]::Match($svgContent, $testCountPattern)
if ($currentVersionMatch.Success -and $currentVersionMatch.Groups[1].Value -eq $version -and $currentTestCountMatch.Groups[2].Value -eq $testCountLabel) {
    Write-Host "Banner already has correct version: v$version"
    Write-Host "Banner already has correct test count: $testCountLabel"
    exit 0
}

# Replace the version and test count in the SVG
$newSvgContent = $svgContent -replace $versionPattern, $newVersionText
$testCountRegex = [regex]$testCountPattern
$newSvgContent = $testCountRegex.Replace($newSvgContent, "`${1}$testCountLabel`${3}", 1)

# Write the updated SVG
# Use .NET WriteAllText for UTF-8 without BOM (cross-platform compatible)
try {
    [System.IO.File]::WriteAllText($svgPath, $newSvgContent)
} catch {
    Write-Error "Failed to write SVG file ${svgPath}: $_"
    exit 1
}

# Stage the modified SVG using git add
try {
    Push-Location $repoRoot
    git add $svgPath
    if ($LASTEXITCODE -ne 0) {
        throw "git add failed with exit code $LASTEXITCODE"
    }
} catch {
    Write-Error "Failed to stage SVG file ${svgPath}: $_"
    exit 1
} finally {
    Pop-Location
}

Write-Host "Updated banner version to: v$version"
Write-Host "Updated banner test count to: $testCountLabel"
exit 0
