name: YAML Format + Lint

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  yaml-checks:
    name: Prettier and yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Prettier check (YAML)
        run: npx -y prettier@3.3.3 --check "**/*.{yml,yaml}"

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: .
          config_file: .yamllint.yaml
          strict: true
